name: uniq-deep
version: 1.1.1
synopsis: uniq-deep
description: alternative of unix uniq command. 'uniq-deep' detect repeated lines unless they are adjacent.
github: ncaq/uniq-deep
category: Console
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

ghc-options:
  - -Wall
  # - -Wall-missed-specialisations
  - -Widentities
  # - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissed-specialisations
  # - -Wmissing-export-lists
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  # - -Wmissing-import-lists
  # - -Wmissing-local-signatures
  # - -Wmonomorphism-restriction
  # - -Wpartial-fields
  - -Wredundant-constraints
  - -Wcompat
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - unordered-containers

executables:
  uniq-deep:
    main: src/Main.hs
