name: uniq-deep
version: 1.1.1
synopsis: uniq-deep
description: alternative of unix uniq command. 'uniq-deep' detect repeated lines unless they are adjacent.
github: ncaq/uniq-deep
category: Console
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: PublicDomain

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers

executables:
  uniq-deep:
    main: src/Main.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -with-rtsopts=-N
