name: uniq-deep
version: 1.2.1
synopsis: uniq-deep
description: alternative of unix uniq command. 'uniq-deep' detect repeated lines unless they are adjacent.
github: ncaq/uniq-deep
category: Console
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - unordered-containers

executables:
  uniq-deep:
    main: src/Main.hs
